# Generated by Django 4.2.13 on 2024-05-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_review_rating_alter_review_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='visit_date',
            field=models.DateField(),
        ),
    ]
