# Generated by Django 4.2.13 on 2024-05-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('time', models.CharField(db_index=True, max_length=255)),
                ('photo', models.CharField(db_index=True, max_length=255)),
                ('phone', models.CharField(db_index=True, max_length=255)),
                ('review_count', models.IntegerField(default=0)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('vegan', models.BooleanField(default=False)),
                ('halal', models.BooleanField(default=False)),
                ('gluten_free', models.BooleanField(default=False)),
                ('lacto_free', models.BooleanField(default=False)),
            ],
        ),
    ]
