# Generated by Django 4.2.13 on 2024-05-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0002_rename_categoryid_category_category_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="categories",
        ),
        migrations.AddField(
            model_name="restaurant",
            name="gluten_free",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="halal",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="lacto_free",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="phone",
            field=models.CharField(db_index=True, default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="restaurant",
            name="photo",
            field=models.CharField(db_index=True, default="nonphoto", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="restaurant",
            name="time",
            field=models.CharField(db_index=True, default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="restaurant",
            name="vegan",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
